### PR TITLE
add `include` to the configuration

### PR DESCRIPTION
**Pull request by lijialiang**
e.g. `include: '\\.module\\.css'`

### CODE REVIEW

**Comment by moimikey** [comment]
```
/home/travis/build/gajus/babel-plugin-react-css-modules/src/index.js
  147:4   error  Missing semicolon                        semi
  152:61  error  Block must not be padded by blank lines  padded-blocks
```

**Comment by moimikey** [comment]
last thing, tests are failing :(

**Comment by lilijialiang** [comment]
you can see the details of the tests. the original testcases run failed in travis-ci. I did not change anything. why ??  :(

**Comment by gajus** [comment]
Addressed by https://github.com/gajus/babel-plugin-react-css-modules/pull/240

**Pull request closed without merging**
