### PR TITLE
Add `silenceStyleNameErrors` option

### LINKED ISSUE #97: Ignore Errors in Testing
I am trying to write some test code using Jest and Enzyme to test out my components. I would like to be able to test that a proptype warning gets thrown when a prop is invalid, but I'm running into the issue where css modules uses the invalid prop to create the stylenames. Is there anyway to ignore these styleName not found errors in a test environment? I noticed that the react-css-modules has a flag for "errorWhenNotFound".

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #97

The main work in this PR is to add a new option that will let users silence the `Could not resolve the styleName...` errors when a `styleName` is not found in a loaded CSS module.  These kinds of errors can be super helpful in development, but during production users may want to prevent crashing their javascript and opt for broken styles instead.

I decided not to use the same option name as react-css-modules [errorWhenNotFound](https://github.com/gajus/react-css-modules#errorwhennotfound), because I find that options which default to `true` are more difficult to implement and reason about.

I've tried to do this as cleanly as possible, but it did involve passing down an options object several levels to `getClassName`, as well as providing that options object in runtime when `silenceStyleNameErrors` is enabled.  If you have suggestions for a better way to do this, please let me know and I'll adjust. 

### Other minor changes
- I've added an `.eslintignore` file that ignores the text fixture files.  My editor kept trying to auto-correct them, and while I could have just turned that feature off, I think it's safer to ignore those files since they don't follow the linting rules anyway.

- I added a small example to the top of the configuration section in the readme, and moved the flow types after the options table.  When I was first setting up this plugin I found it confusing to have those types at the top with no explanation, so hopefully this change is helpful.

### CODE REVIEW

**Comment by gajus** [comment]
My slight problem with this is that `silenceStyleNameErrors` as a boolean operation is all or nothing, e.g. a developer might want to prevent errors from being thrown but want to print an error in the console log.

Therefore, something like `handleNotFoundStyleName` with options "throw", "log" and "ignore" would be a lot more versatile.

What do you think @IanVS ?

**Comment by gajus** [comment]
@IanVS Are you comfortable with this change?

**Comment by IanVS** [comment]
Yes, I think so.  Normally I'm not a fan of string options due to the possibility of typos, but since you've set up option validation that's not really a concern.  I'll work on making the changes within the next few days.  

Question: what would you like to be the default setting?  I assume it should be `"throw"`, to match current functionality, so that's what I'll use unless I hear differently from you.

**Comment by IanVS** [comment]
Apologies that this took a while, but I've updated the PR to add a `handleMissingStyleName` option, with possible values of `"throw"` (default), `"warn"` (console.warn), and `"ignore"` (do nothing).  Please let me know what you think.

**Comment by gajus** [comment]
Just came to complain why this hasn't been done yet, looks like I am stop shopper.

I am joking of course. Sorry, I've overlooked the notification. Looks perfect.

**Comment by IanVS** [comment]
Looks like I made some bugs with this one, sorry about that. I admit I had a bit of a hard time understanding how the various pieces all interact.

**Comment by gajus** [comment]
No worries. Only natural when picking up new code base.

**Pull request merged**
