### PR TITLE
Update filetypes schema to require leading period.

### PR DESCRIPTION
**Pull request by Psykar**

### CODE REVIEW

**Comment by Psykar** [comment]
It's worth nothing your existing schema there was broken according to the spec it seems.
I'm sure this one can be expanded later if required.

**Comment by gajus** [comment]
Correct me if I am wrong, but it should be:

```json
"patternProperties": {
    "\\..*": {"type": "string"}
},
"patternRequired": ["\\..*"]
```

**Comment by Psykar** [comment]
I won't claim to know json schema layouts. But the above threw an error correctly when I left a period off filetypes in my config saying the schema didn't pass.

I can try adding a unit test if you'd prefer? I just threw this together quickly.

**Comment by Psykar** [comment]
This page : http://json-schema.org/example2.html 
has the following
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "/": {}
    },
    "patternProperties": {
        "^(/[^/]+)+$": {}
    },
    "additionalProperties": false,
    "required": [ "/" ]
}
```
And their spiel matches what I'd expect.

**Comment by gajus** [comment]
Thank you

**Pull request merged**
