### PR TITLE
added more information to an error message

### PR DESCRIPTION
**Pull request by CurtisHumphrey**

### CODE REVIEW

**Comment by gajus** [comment]
Generally, I am against providing details in an error. This is a client side application. If error is happening while you are developing the application, use the devtools to inspect the state.

However, if we do provide details, then I'd rather do it in a `console.log`. I have updated the PR. Please tell me if this approach is good with you.

**Comment by CurtisHumphrey** [comment]
I'll have to check to see if that works.  I have had issues with console.log being eaten by babel plugins whereas the error throw always works and works well in test suites...

**Comment by jjinux** [comment]
See: https://github.com/gajus/babel-plugin-react-css-modules/pull/179

**Comment by CurtisHumphrey** [comment]
I think #179 solves what I was after.

**Pull request closed without merging**
