### PR TITLE
Fix the ajv-keywords "keyword select requires $data option" warning.

### LINKED ISSUE #111: keyword select requires $data option
After I updated to version 3.1.0 from 2.8.0 I keep getting this message in console everytime I run building process with webpack.
`keyword select requires $data option`

I don't have and select or option tags in code.

### PR DESCRIPTION
**Pull request by trevorsmith**
Fixes #111.

### CODE REVIEW

**Comment by the-spyke** [comment]
There is another issue:

```
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
```

But is `package.json` I see:

```
"dependencies": {
    "ajv": "^4.11.4",
```

**Comment by the-spyke** [comment]
@trevorsmith Could you try to replace `$data:` with `'$data':` and check if build is still failing?

**Comment by trevorsmith** [comment]
Sorry for the delay, I've been out of town for the weekend.

There are two conflicting linting rules, both of which result in errors:
```js
{ $data: true } // id-match - Identifier '$data' does not match the pattern
{ '$data': true } // quote-props - Unnecessarily quoted property '$data' found
```

I've added an inline comment to disable `id-match`.

**Comment by trevorsmith** [comment]
I've also upgraded ajv to ^5.0.0 after looking over the changelog for any changes that might affect the options schema.

**Pull request merged**
