### PR TITLE
Feature/v6

### PR DESCRIPTION
**Pull request by meglio**
* Update generic-names to 3.0.0
* Adds constributor list to the package.json
* Add CHANGELOG.md listing breaking changes.

### CODE REVIEW

**Comment by gajus** [comment]
Changes are documented in https://github.com/gajus/babel-plugin-react-css-modules/releases

**Comment by meglio** [comment]
Hi @gajus , would you be so share your expectations regarding this PR. You just closed it and commented on one of 3 changes only.

**Comment by kcirtaptrick** [comment]
@meglio Thanks for finding a solution to this!

This has also been causing issues for me for quite some time, if the owner is unresponsive, feel free to make a fork and let me know what the package is if you do.

**Comment by meglio** [comment]
@kcirtaptrick Looks like there is already a fork that is getting some care, please read this thread: https://stackoverflow.com/a/67241915/335304

**Pull request closed without merging**
